FROM ubuntu:24.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install wget sudo -y

WORKDIR /tmp/i2p
RUN wget https://github.com/PurpleI2P/i2pd/releases/download/2.60.0/i2pd_2.60.0-1noble1_amd64.deb -O i2pd.deb -q
RUN apt install ./i2pd.deb -y

RUN rm -rf /tmp/i2p

COPY conf/i2p-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 4444
CMD /entrypoint.sh



